version: "3"
services:
  backflask:
    build: ./backflask
    container_name: 'kylo_api_back_flask'
    command: sh -c 'python app.py'
    ports:
      - '5000:5000'
    volumes:
      - ./backflask:/backflask
    #volumes:
    #  - /home/walter/Descargas/react/backend:/backend
    depends_on:
      - "db-kylo-fr"

  db-kylo-fr:
    container_name: 'db_redis_kylo_fr'
    image: redis
    ports:
      - "6379:6379"

  frontreact:
    build: ./frontreact
    container_name: 'kylo_api_frontreact'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./frontreact:/frontreact
    depends_on:
      - "backflask"
    stdin_open: true
    tty: true