version: "3"
services:
  backend:
    build: ./backend
    container_name: 'kylo_api_back'
    command: sh -c 'npm install; npm start'
    ports:
      - '3002:3002'
    volumes:
      - ./backend:/backend
    #volumes:
    #  - /home/walter/Descargas/react/backend:/backend
    depends_on:
      - "db-kylo"

  db-kylo:
    container_name: 'db_redis_kylo'
    image: redis
    ports:
      - "6379:6379"

  fronted:
    build: ./fronted
    container_name: 'kylo_api_front'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./fronted:/fronted
    depends_on:
      - "backend"
    #working_dir: /home/walter/Descargas/react/fronted
    stdin_open: true
    tty: true
    #environment:
    #  - NODE_ENV=development
    #  - CHOKIDAR_USEPOLLING=true