version: "3"
services:
  web-app-flask:
    build: .
    container_name: 'sw_api_f'
    command: sh -c 'python app.py'
    ports:
      - '5000:5000'
    volumes:
      - /home/walter/Descargas/api_flask/api:/api
    depends_on:
      - "db-redis"

  db-redis:
    container_name: 'db_sw_api_f'
    image: redis
    ports:
      - "6379:6379"
